![imagen](./img/ejercicios.png)

# Ejercicio SQL
Para este ejercicio usaremos una base de datos de Pokemon. **Asegúrante que tienes el CSV "pokemon.csv" en la misma carpeta donde está este Notebook**. Realiza los siguientes apartados:

1. Obten una tabla con todos los campos
2. Obten una tabla con los campos "Name", "Type 1", "Type 2"
3. Obten la misma tabla que el apartado anterior, pero en este caso renombrando los campos al castellano.
4. ¿Cuales son todos los "Type 1" diferentes?
5. ¿Cuales son todos los "Type 1" y "Type 2" diferentes?
6. ¿Cuáles son los pokemon de agua? "Type 1" = "Water"
7. Obtén una tabla con los pokemon legendarios
8. Obtén una tabla con los pokemon legendarios de fuego ("Type 1" = "Fire")
9. Obtén una tabla con los pokemon cuyo nombre empieze por "W" y tenga una defensa mayor de 100 puntos
10. Saca una tabla con los pokemon de la primera generación, que NO sean "Type 1" = "Psychic" y tengan una velocidad superior a 130
11. ¿Cuál es el pokemon con el ataque más alto?
12. ¿Cuál es la media de la defensa de todos los pokemon?
13. ¿Cuál es la media de la defensa por generación?
14. Calcula el máximo HP por "Type 1"

**NOTA**: se recomienda añadir un `LIMIT 5` en la mayoría de apartados para evitar grandes outputs de las queries.

In [8]:
# Importamos paquetes
import pandas as pd
import sqlite3
cnx = sqlite3.connect(':memory:')

# Importamos datos de un CSV
df = pd.read_csv('pokemon.csv')
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [9]:
# Pasamos el DataFrame de Pandas a SQL
df.to_sql('pokemon', con=cnx, if_exists='append', index=False)

# Definimos la función para hacer queries.
def sql_query(query):
    return pd.read_sql(query, cnx)

In [10]:
# 1. Obten una tabla con todos los campos
query = """
    select * from pokemon
"""
sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,0
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,0
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,0
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,0
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,1
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,1
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,1
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,1
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1

In [ ]:
# 2. Obten una tabla con los campos "Name", "Type 1", "Type 2"
query = '''
    select Name, [Type 1], [Type 2] from pokemon
'''
sql_query(query)

                      Name   Type 1  Type 2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[800 rows x 3 columns]

In [9]:
# 3. Obten la misma tabla que el apartado anterior, pero en este caso renombrando los campos al castellano.
query = '''
   select Name as Nombre, [Type 1] as [Tipo 1], [Type 2] as [Tipo 2]  from pokemon
'''
sql_query(query)

                    Nombre   Tipo 1  Tipo 2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[800 rows x 3 columns]

In [ ]:
# 4. ¿Cuales son todos los "Type 1" diferentes?
query = '''
    select distinct [Type 1] from pokemon
'''
sql_query(query)

      Type 1
0      Grass
1       Fire
2      Water
3        Bug
4     Normal
5     Poison
6   Electric
7     Ground
8      Fairy
9   Fighting
10   Psychic
11      Rock
12     Ghost
13       Ice
14    Dragon
15      Dark
16     Steel
17    Flying

In [12]:
# 5. ¿Cuales son todos los "Type 1" y "Type 2" diferentes?
query = '''
    select distinct [Type 1],[Type 2] from pokemon
'''
sql_query(query)

      Type 1  Type 2
0      Grass  Poison
1       Fire     NaN
2       Fire  Flying
3       Fire  Dragon
4      Water     NaN
..       ...     ...
149    Ghost   Grass
150   Flying  Dragon
151  Psychic   Ghost
152  Psychic    Dark
153     Fire   Water

[154 rows x 2 columns]

In [13]:
# 6. ¿Cuáles son los pokemon de agua? "Type 1" = "Water"
query = '''
    select Name from pokemon where [Type 1]="Water"
'''
sql_query(query)

                        Name
0                   Squirtle
1                  Wartortle
2                  Blastoise
3    BlastoiseMega Blastoise
4                    Psyduck
..                       ...
107                  Froakie
108                Frogadier
109                 Greninja
110                Clauncher
111                Clawitzer

[112 rows x 1 columns]

In [6]:
# 7. Obtén una tabla con los pokemon legendarios
query = '''
    select * from pokemon where Legendary
'''
sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,1
1,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,1
2,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,1
3,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,1
4,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,1
61,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,1
62,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,1
63,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,1
64,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1

In [16]:
# 8. Obtén una tabla con los pokemon legendarios de fuego ("Type 1" = "Fire")
query = '''
    select * from pokemon where Legendary=1 and [Type 1]="Fire"
'''
sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,1
1,244,Entei,Fire,NaN,580,115,115,85,90,75,100,2,1
2,250,Ho-oh,Fire,Flying,680,106,130,90,110,154,90,2,1
3,485,Heatran,Fire,Steel,600,91,90,106,130,106,77,4,1
4,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1

In [20]:
# 9. Obtén una tabla con los pokemon cuyo nombre empieze por "W" y tenga una defensa mayor de 100 puntos
query = '''
    select * from pokemon where Name like "W%" and Defense>100
'''
sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,110,Weezing,Poison,NaN,490,65,90,120,85,70,60,1,0
1,413,WormadamSandy Cloak,Bug,Ground,424,60,79,105,59,85,36,4,0

In [19]:
# 10. Saca una tabla con los pokemon de la primera generación, que NO sean "Type 1" = "Psychic" y tengan una velocidad superior a 130
query = '''
    select * from pokemon where Generation=1 and not [Type 1]="Psychic" and Speed>130
'''
sql_query(query)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,0
1,101,Electrode,Electric,NaN,480,60,50,70,80,80,140,1,0
2,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,0

In [7]:
# 11. ¿Cuál es el pokemon con el ataque más alto?
query = '''
    select Name,max(Attack) from pokemon
'''
sql_query(query)

                  Name  max(Attack)
0  MewtwoMega Mewtwo X          190

In [26]:
# 12. ¿Cuál es la media de la defensa de todos los pokemon?
query = '''
    select avg(Defense) from pokemon
'''
sql_query(query)

   avg(Defense)
0       73.8425

In [ ]:
# 13. ¿Cuál es la media de la defensa por generación?
query = '''
    select Generation,avg(Defense) as [Mean Defense] from pokemon group by Generation
'''
sql_query(query)

   Generation  Mean Defense
0           1     70.861446
1           2     73.386792
2           3     74.100000
3           4     78.132231
4           5     72.327273
5           6     76.682927

In [31]:
# Apartado 14. Calcula el máximo HP por "Type 1"
query = '''
    select "Type 1", max(HP) as "Max HP" from pokemon group by "Type 1"
'''
sql_query(query)

      Type 1  Max HP
0        Bug      86
1       Dark     126
2     Dragon     125
3   Electric      90
4      Fairy     126
5   Fighting     144
6       Fire     115
7     Flying      85
8      Ghost     150
9      Grass     123
10    Ground     115
11       Ice     110
12    Normal     255
13    Poison     105
14   Psychic     190
15      Rock     123
16     Steel     100
17     Water     170